import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useTranslation from 'next-translate/useTranslation'
import { useRouter } from 'next/router'
import { Container, Row, Col, Link as NextUiLink } from '@nextui-org/react'
import Link from 'next/link'

const Home: NextPage = () => {
    const router = useRouter()
    const { t, lang } = useTranslation('common')

    return (
        <Container>
            <Head>
                <title>FixedIt</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Row>
                <Container>
                    <h1>{t('greeting')}</h1>
                </Container>
            </Row>
            <Row>
                <footer className={styles.footer}>
                    <ul>
                        {router.locales?.map((locale) => (
                            <li key={locale}>
                                <Link
                                    passHref
                                    href={router.asPath}
                                    locale={locale}
                                >
                                    <NextUiLink block color="success">
                                        {locale}
                                    </NextUiLink>
                                </Link>
                            </li>
                        ))}
                    </ul>
                </footer>
            </Row>
        </Container>
    )
}

export default Home
